### ISSUE TITLE
Fix support for multi-root workspaces

### ISSUE THREAD

**Issue by jonasclement** [swellaby/vscode-workspace-config-plus#76]
Some settings don't get applied in `$PROJECT_DIR/.vscode/settings.json` when you're working in a multi-root workspace. It would be nice to have settings copied into the workspace file when editing `settings.{shared|local}.json`, if possible 🙂 

This does present an additional challenge with nested projects (for example when using Git submodules). If a sub-directory has it's own settings, those should ideally be merged into the workspace file's settings as well.

**Comment by calebcartwright** [comment]
Thanks for sharing! We have done some testing in multi-root workspaces to validate core behavior and haven't observed any issues ourselves.

Could you please elaborate on the specific issue you're seeing, ideally with a minimal repro case?

**Comment by jonasclement** [comment]
Sure!

The issue that my team and I are experiencing is something like this:

Project structure
```
someproject
|-.vscode
|--settings.{local|shared}.json
|
|-someproject-api [submodule]
|--.vscode
|---settings.{local|shared}.json
|--(other API codebase config stuff)
```

For this setup to work ideally for us, `someproject-api` should be made a workspace root in Visual Studio Code, as that allows it to carry it's own config, independently of the `someproject` codebase, if you work on them separately, while also applied when working on them together.

Some settings, such as one from the `Volar` extension, `volar.vueserver.useSecondServer` does not work if applied in `someproject/.vscode/settings.json` in a multi-root workspace, and Visual Studio Code informs the user of this if you hover over the key in `settings.json`. It should be put into the Workspace file's `settings` section instead. With this extension, that doesn't seem to happen.

The additional challenge with submodules would be somehow merging the appropriate settings from `someproject/.vscode/settings.{local|shared}.json` with the settings in `someproject-api/.vscode/settings.{local|shared}.json`, and having those end up in the `settings` section of the workspace file together. :)

**Comment by calebcartwright** [comment]
Thanks for the response, but I'm still not convinced I follow.

This extension operates on a project/workspace folder by project/workspace folder basis within a multi-root workspace, and should provide support for each individual project/workspace folder to use its respective set of local/shared files.

This extension does not attempt to elevate/merge settings defined in individual project/workspace folders up to the workspace global level settings.

My impression is that you were expecting this extension to do the latter (or perhaps are suggesting a feature request to do so), but it's not clear to me whether you're also reporting a bug with the former.

**Comment by calebcartwright** [comment]
Closing given the age of the issue but feel free to follow up with any clarifications or questions!
